server:
  port: 8888

jwt:
  issuer: ${jwt.issuer}
  secretKey: ${jwt.secretKey}
  header: ${jwt.header}
  expire:
    access: ${jwt.expire.access}
    refresh: ${jwt.expire.refresh}

aes:
  key: devh0000000000000000000000000000
  
auth:
  key: 
    size: 16

spring:
  sql:
    init:
      mode: always
#      schema-locations: classpath*:sql/schema-${database}.sql
      data-locations: classpath*:sql/data-${database.database}.sql
  datasource:
#    url: jdbc:h2:tcp://localhost/~/dev/tools/h2/db/auth
#    driver-class-name: org.h2.Driver
#    username: sa
    url: ${database.url}
    driver-class-name: ${database.driverClassName}
    username: ${database.username}
    password: ${database.password}
  jpa:
    defer-datasource-initialization: true # hibernate create -> schema.sql -> data.sql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  redis:
    host: localhost
    port: 6379
  mail:
    host: ${mail.host}
    port: ${mail.port}
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          starttls:
            enable: ${mail.smtp.starttls.enable}
            required: ${mail.smtp.starttls.required}
          auth: ${mail.smtp.auth}
          connectiontimeout: ${mail.smtp.connectiontimeout}
          timeout: ${mail.smtp.timeout}
          writetimeout: ${mail.smtp.writetimeout}