server:
  port: 8888

jwt:
  issuer: ${jwt.issuer}
  secretKey: ${jwt.secretKey}
  header: ${jwt.header}
  expire:
    access: ${jwt.expire.access}
    refresh: ${jwt.expire.refresh}

aes:
  key: devh0000000000000000000000000000
  
auth:
  key: 
    size: 16


spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/dev/tools/h2/db/auth
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  redis:
    host: localhost
    port: 6379
  mail:
    host: ${mail.host}
    port: ${mail.port}
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          starttls:
            enable: ${mail.smtp.starttls.enable}
            required: ${mail.smtp.starttls.required}
          auth: ${mail.smtp.auth}
          connectiontimeout: ${mail.smtp.connectiontimeout}
          timeout: ${mail.smtp.timeout}
          writetimeout: ${mail.smtp.writetimeout}