version: '3.7'

services:
  mariadb:
    image: mariadb:${MARIADB_VERSION}
    container_name: mariadb-${ID}
    command: --lower_case_table_names=1
    environment:
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PW}
      - MYSQL_DATABASE=${MARIADB_SCHEMA}
      - MYSQL_USER=${MARIADB_USER}
      - MYSQL_PASSWORD=${MARIADB_PW}
    volumes:
      - ${MARIADB_VOLUME}:/var/lib/mysql
    ports:
      - '${MARIADB_EXT_PORT}:3306'
    networks:
      - devh-network
  redis:
    image: redis:${REDIS_VERSION}
    container_name: redis-${ID}
    volumes:
      - ${REDIS_VOLUME}:/data
#      - ./conf/redis.conf:/usr/local/conf/redis.conf
    ports:
      - '${REDIS_EXT_PORT}:6379'
networks:
  devh-network:
    external: true

